### ISSUE TITLE
bower: ENOTFOUND Package angular-ui-ace\ not found

### ISSUE THREAD

**Issue by jxc876** [angular-ui/ui-ace#108]
I tried to install ui-ace via bower on my Windows command prompt: 

    C:\tmp\bower > bower install angular-ui-ace\#bower 

but it gave me an error:

`bower                        ENOTFOUND Package angular-ui-ace\ not found`

When I ran the same command from my bash shell it works fine:

    bower angular-ui-ace#bower  not-cached git://github.com/angular-ui/ui-ace.git#bower 
    ...
    bower angular-ui-ace#bower          install angular-ui-ace#36844ff7c0
    bower ace-builds#^1                 install ace-builds#1.1.9
    bower angular#~1.x                  install angular#1.3.15

I think it might be related to windows interpreting the `\`, I tried using quotes, double \\, escaping:

* `bower install 'angular-ui-ace\#bower'`
* `bower install angular-ui-ace\\#bower`
* `bower install angular-ui-ace/#bower`
* `bower install angular-ui-ace/\#bower`

What is the correct syntax to install ui-ace via bower on a windows command prompt?

**Comment by douglasduteil** [comment]
Did you try `bower install angular-ui-ace` or `bower install angular-ui-ace#bower` ?

**Comment by jxc876** [comment]
Thanks douglas, that did the trick.
