### ISSUE TITLE
Editor doesn't render if initially hidden

### ISSUE THREAD

**Issue by nkerkin** [angular-ui/ui-ace#18]
Check out this plunker http://plnkr.co/edit/zNdlc3jts4a8w3kS08uw?p=preview

The second editor doesn't render until you make a modification.

**Comment by RaphaelRheault** [comment]
I found a similar problem when using ui-ace with ng-show in a ng-repeat.
It's probably related to this bug.
http://plnkr.co/edit/7BAtJ8vq0zP5rqbmcti6?p=preview

**Comment by RaphaelRheault** [comment]
Found a solution : use ng-if instead of ng-show. Everything works fine that way.

**Comment by douglasduteil** [comment]
Alright It might be because Ace has to be refreshed when using ng-show/hide with the `resize` function
