### ISSUE TITLE
Inserting text in Ace Editor via Protractor throws error

### ISSUE THREAD

**Issue by ashitvora-zz** [angular-ui/ui-ace#182]
I am trying to run an automated test and one of the steps of a test case is to clear the Ace Editor and insert text in it.

Earlier I had regular content editable DIV and I was able to insert text in it but not anymore after switching to Ace Editor.

All I am doing is calling "clear" method on the element and then "sendText" on it. I tried adding "click" method before clear to make sure Ace Editor does have the focus and it did bring the focus to Ace Editor but it still throws an error that element should be user-editable to clear it.

I also tried putting a sleep of 5s before clearing it just in case, Clearing is getting triggered before Ace makes the div contenteditable.

Here's the exact error to be precise.
`Failed: invalid element state: Element must be user-editable in order to clear it.`

**Comment by Ugoku** [comment]
I ran into this today, instead of doing `element(by.css('#myAceEditor')).clear();` I fixed it by doing `element(by.css('#myAceEditor textarea')).clear();`

**Comment by ashitvora-zz** [comment]
Worked for me.
