### ISSUE TITLE
Use without bower?

### ISSUE THREAD

**Issue by LoganDark** [angular-ui/ui-ace#186]
How do I use this without bower? I prefer `npm`. Is `npm` supported?

**Comment by smellai** [comment]
yes https://www.npmjs.com/package/angular-ui-ace

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/49935207-4a922f80-fe85-11e8-8031-f7296984ef99.png)

**Comment by smellai** [comment]
just do 
```
npm install angular-ui-ace
```

**Comment by LoganDark** [comment]
K
