### ISSUE TITLE
Update Ace

### ISSUE THREAD

**Issue by gkoberger** [angular-ui/ui-ace#28]
Seems like ace has stopped tagging releases in [ajaxorg/ace-builds](https://github.com/ajaxorg/ace-builds/) (last one was 8 months ago), despite lots of new updates being released.

Would it be possible to update `ui-ace`'s dependencies to just use the latest from `ace-builds`?

**Comment by douglasduteil** [comment]
To prevent future version conflict I'll stick with tag versions sorry.
But you can force bower to use the *master* branch if you need those new updates.

```bash
bower install ace-builds#master
```
