### ISSUE TITLE
Support fontSize

### ISSUE THREAD

**Issue by cmoulliard** [angular-ui/ui-ace#33]
I propose to support also this option

        if (angular.isDefined(opts.fontsize)) {
          acee.setFontSize(opts.fontsize);
        }

That we could use as aceOption : 

  $scope.aceOption = {
      mode:     'xml',
      theme:    $scope.theme.toLowerCase(),
      fontsize: '18px',

**Comment by douglasduteil** [comment]
The new `rendererOptions` will do

Demo : http://plnkr.co/edit/TR9bRFDhYC8GH3hx068n
