### ISSUE TITLE
the editor using autocomplete not well

### ISSUE THREAD

**Issue by login4all** [angular-ui/ui-ace#51]
I tried to add autocomplete to editor like in examples on ace page
[ace homepage](http://ace.c9.io/#nav=about&api=editor) (_when i press ctrl+space i see variants from snippets_)
by following instructions on [ace wiki page](https://github.com/ajaxorg/ace/wiki/How-to-enable-Autocomplete-in-the-Ace-editor)
but it would't work well: [jsfiddle](jsfiddle.net/login4all/2aMk2/14/)
(_i can`t see autocomplete box, but can select one of the variants by using arrow keys_)

**Comment by bjdash** [comment]
The specified plunker is not working
