### ISSUE TITLE
Specify font family or families and font size?

### ISSUE THREAD

**Issue by andrewboni** [angular-ui/ui-ace#71]
I didn't see an easy way to do this. I tried the obvious, with no luck:
```coffeescript
  $scope.uiAceConfig =
    useWrapMode : true
    showGutter: true
    theme: 'twilight'
    mode: 'html'
    fontFamily: 'Inconsolata'
    fontSize: '16px'
```

```html
<div ui-ace="uiAceConfig" ng-model="content.html"></div>
```

Anyone find a way to do this? Thanks!

**Comment by kbsymanz** [comment]
The source shows that it does have an option for advanced configuration for other options such as fontsize, etc. This is done with the ```advanced``` element in the configuration for ui-ace.

Using your example:

```javascript
$scope.uiAceConfig = {
    useWrapMode : true,
    showGutter: true,
    theme: 'twilight',
    mode: 'html',
    advanced: {
        fontFamily: 'Inconsolata',
        fontSize: '16px'
    }
};
```

**Comment by PowerKiKi** [comment]
Thanks @kbsymanz for providing an answer

**Comment by andrewboni** [comment]
@kbsymanz were you actually able to get it working? I have:
```coffeescript
    $scope.uiAceConfig =
      useWrapMode : true
      showGutter: true
      theme: 'solarized_dark'
      mode: 'html'
      onLoad: $scope.aceLoaded
      onChange: $scope.aceChanged
      workerPath: '/assets/lib/jsoneditor/ace'
      advanced:
        fontFamily: 'Inconsolata'
        fontSize: '22px'
```

But the `advanced: {}` property isn't getting picked up, as the `font-family` and `font-size` css properties are the same. Was anyone able to get this working?

**Comment by kbsymanz** [comment]
@andrewboni : Yes it is working for me. Here is the entire template file that I am using it in and the fontSize setting definitely changes the font-size.

```
<div id="editorWrapper" ng-hide="editorHidden">
  <div id="editorInstance" ng-model="selectedNote.note" ui-ace="{
  useWrapMode: true,
  showGutter: true,
  theme: 'solarized_light',
  mode: 'markdown',
  onLoad: aceLoaded,
  onChange: aceChanged,
  advanced: {
    fontSize: 40
  }
}"></div>
</div>
```

I am using Angular 1.3.13 and angular-ui-ace 0.2.3.
